### ISSUE TITLE
Test scenario [#2]: Use vouchers to do a transaction

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/scauting#10]
Objective: Using a voucher to do a transaction is one of the core functionalities of the platform. This should be tested before every release.

# Environment

* Branch: Release v0.9.0
* Database: Staging

# Pre-conditions

1. Me-app (alpha version) installed on iOS device.
2. Me-app (alpha version) installed on Android device.

# Direct URL(s)

1. https://berkelland.staging.forus.io

# Input data

1. Requester profile (e-mail)
    * berkelland@asdasd.nl
2. Provider profile (e-mail)
    * provider_ww@asdasd.nl

# Prerequisites

1. Acces to accepted provider profile
2. Sufficient amount on the voucher

# Instructions

<table>
<tr><th>Step No.</th><th>Step description</th><th>Expected result</th></tr>
<tr><td>1.</td><td>Go to the webshop, click <b>Login</b>, enter your mailaddress and click <b>Volgende</b></td><td>Login modal open with an input field to enter e-mailaddress. Login mail should be send to the mailbox. </td></tr>
<tr><td>2.</td><td>Open the mail and click the link to login</td><td>The webshop page should open and user is logged in</td></tr>
<tr><td>3.</td><td>Click on <b>Mijn vouchers</b> and click on the Budget voucher top open the voucher</td><td>Redirection the voucher page and the voucher should open with the Qr-code.</td></tr>
<tr><td>4.</td><td>Open the Me-app with provider acces and scan the Qr-code.</td><td>The provider should see a new screen with the option to enter the amount of the transaction and the possibility to confirm the transaction</td></tr>
<tr><td>5.</td><td>Enter an amount and confirm the transaction by clicking on <b>Verzoek tot betaling</b></td><td>The provider provider should see a confirmation screen with a succes message.</td></tr>
<tr><td>6.</td><td>Refresh the voucher page to check if the budget is reduced by the amount of the transaction</b></td><td>The budget of the voucher should be reduced with the amount of the transactions and the user should get a notification of this transaction.</td></tr>
</table>

# Result

* pass

# Notes

* use right email with provider access

**Comment by MariskaMartens** [comment]
**Result:**
Pass

**Notes:**
- Step 4: Ik kreeg een autorisatie code op de Me-app om in te loggen, maar dacht dat het handiger zou zijn om in te loggen via e-mail. Ik klikte op die knop, vulde e-mail in (provider_ww@asdasd.nl) (op mobiel) en klikte op de link in de e-mail (via mijn laptop). Alleen nu logt hij niet in op mijn mobiel, hij probeert me nu op de laptop in te loggen op de Me-app die daar niet op staat. Inloggen op deze manier werkt dus niet op deze methode (combinatie mobiel en laptop). MAAR het werkt wel goed als ik Chrome op mobiel open en daarmee inlog en op de knop "Open me.app" druk.

**Comment by marten410** [comment]
ik had in het begin moeite met het inloggen in de app maar dat lag aan mij, verder ging het prima.
![betaling](https://user-images.githubusercontent.com/58295805/75240796-3b1ab000-57c5-11ea-8419-e8e49ca9f5a9.PNG)

**Comment by PirateRalla** [comment]
**Result**: pass

----------------------------
**Algemene indruk**

Zojuist met succes € 15,- uitgegeven XD
De app Me is wel even wennen, het voelt een beetje als een 'uitgeklede' app. Accountgegevens, logout, of zoiets als een uitleg wat bijvoorbeeld 'records' zijn, is moeilijk tot niet te vinden. Er wordt geen gebruik gemaakt van grafische hulpmiddelen, waardoor het vooral erg zoeken en trial-en-error wordt om het beoogde resultaat te bereiken. Prima voor mij als tester, maar minder als je daadwerkelijk afhankelijk bent van deze app voor je uitgaven. 
Naar mijn gevoel is de app op dit moment vooral (of eerder alleen) gericht op de consument, en niet op de middenstander die via deze app zou moeten declareren. Dit kan ondervangen worden met handleidingen, maar misschien is het verstandig de app twee verschillende lay-outs te geven afhankelijk van het account van de gebruiker (consument of aanbieder). Dit omdat fout gefactureerde bedragen zowel de middenstander als de gebruiker kunnen schaden, en dit moeilijk is te rectificeren zonder daarbij het risico op fraude te verhogen.

**Pluspunten:**
-App en site functioneren als behoort. 
-Afschrijvingen via de QR code worden direct verwerkt.

**Minpunten**
-App erg basic, geen visuele/grafische hulpmiddelen of helpfunctie en daarmee weinig intuïtief
-App sterk gericht op consument
-Afschrijvingen onder vouchers op de website geven geen details/omschrijving aan van de specifieke verkoper. *
-Geen duidelijke mogelijkheid voor de verkoper om fouten te rectificeren. Wat als een medewerker een verkeerd bedrag heeft ingevoerd? Hoe draait men dat terug? Men kan geen negatieve bedragen invoeren om daarmee geld te restitueren.

             *Bijvoorbeeld, ik kan als bedrijf geen opmerkingen of nota's bijvoegen aan de afschrijving via de app. Op de website staat daardoor alleen de algemene bedrijfsnaam en het afgeschreven bedrag, geen verdere specificaties. Zelfs adresgegevens zijn niet via dat scherm te bereiken. 
Dit kan op later tijdstip tot verwarring leiden. Wanneer de consument 1,5 maand later een afschrijving ziet van zoiets ondoorzichtigs als "Handelsonderneming Jansema" is het maar de vraag of de consument direct de aankoop kan identificeren. 


**Suggesties**
- Het sturen van een betaalbevestiging of factuuroverzicht per mail aan zowel bedrijf, consument als gemeente. Dit is prettiger voor de administratie, en met name voor bedrijven kan het uitblijven van een dergelijke functie een reden zijn niet aan het programma mee te doen.

**Comment by PirateRalla** [comment]
PS => Ik zag dat ik op mijn asdasd.nl e-mail wel een bevestiging van de uitgave heb ontvangen, maar hier staat alleen mijn nieuw huidig totaal op. Het zou misschien iets vollediger zijn om ook te vermelden welk bedrag is afgeschreven?
![Naamloos](https://user-images.githubusercontent.com/61502712/75358502-4815cd00-58b3-11ea-9115-cd59545fe822.png)
