### ISSUE TITLE
Test scenario [#3]: Sign up flow provider | URL Filter

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/scauting#11]
Objective: Use this template to check if the URL for the signup flow works properly.

# Environment

* Branch: Release v0.9.0
* Database: Staging

# Pre-conditions

1. Funds need to be configured
2. Three pre made filters based on the filter options.

The URL filter can be filtered based on:
- Tags
- Organization ID
- Fund ID

# Direct URL(s)
1. Tag: https://staging.forus.io/provider/sign-up?tag=sdoa 
-> 13 regelingen
2. Organization ID: https://staging.forus.io/provider/sign-up?fund_id=9 
-> Sociaal culturele en sportieve activiteiten
3. Fund_id: https://staging.forus.io/provider/sign-up?organization_id=325 
-> 5 regelingen uitgegeven door gemeente Berkelland
4. https://asdasd.nl (used for temporarily mail-address)
5. https://developers.kvk.nl/documentation/profile-v2-test (used for test kvk number)

# Input data

1. E-mail address
    * signup@asdasd.nl
2. Phone number
    * 0621372826
3. KvK
    * 90001354
4. IBAN number 
    * NL60BUNQ2025316305
5. Remaining data to fill in signup flow.

# Prerequisites

1. Unregistered kvk number

# Instructions

<table>
<tr><th>Step No.</th><th>Step description</th><th>Expected result</th></tr>
<tr><td>1.</td><td>Go to one the URL described above</td><td>Page of the sign up flow should open with a step indication (1 of 7)</td></tr>
<tr><td>2.</td><td>Enter phone number, click <b>Versturen</b> , install the Me-app by using the link received on the phone and checkmark the sentence: 
<b>DE APP IS NU AAN HET DOWNLOADEN. / DE APP IS GEINSTALLEERD.</b> to go the the next step.</td><td>Sign up flow shows a succes message, phone number should receive a sms link that redirects to the app or playstore. Redirection to the next step (2 of 7) </td></tr>
<tr><td>3.</td><td>Enter requested data (mail-address twice, first and last name) an click <b>Volgende</b> button to continue</td><td>Redirection to the next page (step 3 of 7)</td></tr>
<tr><td>4.</td><td>Enter the requested data of the signup form. 1. Organisation name.<br> 2. Bank account number.<br> 3. Mail address.<br> 4. phone number.<br> 5. Website <br> 6. Organization type. <br> 7. KvK number.<br> After entering requested data click on <b>Volgende</b></td><td>Redirection to the step to add an office (4 of 7)</td></tr>
<tr><td>5.</td><td>Check address created by KvK connection. Add business hours and click <b>Volgende</b> to continue</td><td>Redirection to next step (5 of 7)</td></tr>
<tr><td>6.</td><td>Connect the profile to the app. Open Me-app, press <b>IK HEB EEN PROFIEL</b>. Enter the authorisation code displayed by the me app into the sign up flow and click <b>Volgende</b> to initiate the connection with the me app. </td><td>The Me-app should display a message with the notification about sharing bug reports. The sign up flow should go to the next step. (6 of7)</td></tr>
<tr><td>7.</td><td>Scan the QR-code with the Me-app for test purpose</td><td>Me-app displays a succes message and the sign up flow should redirect to next step (7 of 7)</td></tr>
<tr><td>8.</td><td>Choose a fund to apply on and click <b>Bevestig</b>. To continue to dashboard click on <b>Volgende</b></td><td>Modal should open with a confirmation message. After clicking <b>Bevestig</b> the modal should close and the user should see the same page with an indication of the application. After clicking <b>Volgende*</b> the dashboard should open.</td></tr>
</table>

# Result

* Pass

# Notes

* **Volgende** in step 7 is "sla over en ga naar dashboard"

**Comment by Evan-Scauting** [comment]
<strong>Let op bij stap 2!</strong> Je krijgt een SMS met een link die je doorverwijst naar de APP uit de playstore. Je kunt deze installeren maar is verder NIET te gebruiken voor de opdrachten. Maak hiervoor gebruik van de eerder geinstalleerde app. Voor android <a href="https://drive.google.com/file/d/1rP6ALApMVI2v52_BhGBXc-oplona4ZAR/view?usp=sharing"> klik hier</a> Voor Me-iOS: Stuur Gerben een bericht via Rocket.Chat.

**Comment by marten410** [comment]
Het lukte prima om zonder de mobiele app als provider een account te maken.

**Comment by MariskaMartens** [comment]
**Result:**
Pass (inloggen via mobiele app werkt).

**Notes:**
- Step 2: Ik heb het mobiele nummer van de Input data gebruikt, dus geen idee of je een sms kreeg.
- Step 3: Ik heb het e-mailadres signup1@asdasd.nl gebruikt omdat de normale signup al in gebruik is.
- Step 4: Er staat (als je er voor kiest om een afbeelding te uploaden) dat de afbeelding minimaal 400 bij 400 pixels moet zijn. Maar het lijkt erop dat 292x283 px ook werkte bij mij. Bij de volgende stap had ik een afbeelding groter dan 400x400 gebruikt en dat werkte ook.
- Step 3/8: In step 3 heb ik bij de "organisatie aanmaken" aangevinkt dat mijn e-mailadres publiek gemaakt mag worden. Als ik bij step 8 op organisatie bewerken klik, staat het vakje uit terwijl die aan zou moeten staan. Ik heb hier nu in step 8 aangevinkt om mijn telefoonnummer publiek te maken, maar als ik weer terug naar bewerken ga staat het weer uit. [Zie foto1 en foto 2 hier onder]

Foto 1:
![test24feba1](https://user-images.githubusercontent.com/58296023/75154055-1e22a600-570d-11ea-8ba1-78b3d3f5d4a5.png)
^Hier is te zien hoe ik heb aangevinkt dat mijn e-mail adres publiek mag zijn. 
Foto 2:
![test24feba1b](https://user-images.githubusercontent.com/58296023/75154148-604be780-570d-11ea-8907-9118e27ce1da.png)
^Hier is te zien hoe het uit staat bij "organisatie bewerken", terwijl het aan zou moeten staan. Ook na dit te bewerken blijft het uit staan als je terug gaat naar organisatie bewerken.

- Step 5/8: Ook heb ik in step 5 (voor de vestiging) een foto gekozen, maar in het dashboard met mijn vestigingen (step 8) is de foto van mijn vestiging niet terug te zien. [Zie foto's 3 en 4 hier onder].
- ^Step 8: Als ik vervolgens via de vestiging bewerken een foto kies, werkt het wel. Het is dus wel mogelijk om een foto te kiezen voor de vestiging als je hem bewerkt, maar bij het aanmelden werkte het niet. [Zie foto 5 hier onder om te zien dat het daarna wel werkt]/

Foto 3:
![test24feba2](https://user-images.githubusercontent.com/58296023/75154058-1ebb3c80-570d-11ea-9b58-ca4fcab409e3.png)
^Hier is te zien hoe ik een afbeelding heb geüpload voor mijn vestiging.
Foto 4:
![test24feba3](https://user-images.githubusercontent.com/58296023/75154060-1f53d300-570d-11ea-89d0-bb3753f3b137.png)
^Hier is te zien hoe de afbeelding er ineens niet meer bij staat bij mijn vestigingen overzicht.
Foto 5:
![test24feba4](https://user-images.githubusercontent.com/58296023/75154061-1fec6980-570d-11ea-8817-5933f5e60b23.png)
^Hier is te zien hoe de afbeelding er nu wél staat nadat ik de organisatie bewerkt heb.

**Comment by marten410** [comment]
ik kon nu wel de mobiele app gebruiken en het ging prima. verder heb ik niks te vertellen.

**Comment by maxvisser** [comment]
Thanks Mariska; ik zal gerben even vragen om het te reproduceren. Gek dat tie bepaalde zaken niet lijkt op te slaan bij het aanmelden. (zoals afbeeldingen en publiek/prive instellingen)

**Comment by PirateRalla** [comment]
**Result** pass

In alle eerlijkheid is de site zelf een stuk duidelijker dan de omschrijving bij dit test scenario ;-)
Op zich wijzen alle stappen zichzelf. Gewoon een kwestie van de gevraagde gegevens in de bijbehorende vakjes invullen, en op volgende klikken. Een simpele, bekende procedure. 
Alleen stap 6/7 is mij een compleet raadsel. Waarom direct die wisselwerking met app/site?
Waarom kun je prima inloggen op de app zonder deze te hebben gekoppeld met de Authorization code? Waarom kun je geen Authorization Code per mail ontvangen als je op de site werkt?
De aanvrager binnen een bedrijf hoeft niet noodzakelijkerwijze ook de beheerder te zijn van het apparaat waar de uiteindelijke app op wordt geïnstalleerd. En niet iedereen wil werkapps op prive apparatuur installeren. Naar mijn mening kan het aanmaken van een account het beste worden los gemaakt van het koppelen van een apparaat. Dit biedt alleen maar ruimte voor misverstanden.
