### ISSUE TITLE
Test scenario [#4]: Add products to the webshop

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/scauting#12]
Objective: Add products to the webshop

# Environment

* Branch: Release v.0.9.0
* Database: Staging

# Pre-conditions

1. Active fund
2. The sponsor should have accepted the provider before you add products to the webshop
2. Always follow *Test scenario [#3]* before doing this test

# Direct URL(s)

1. https://staging.forus.io/provider
2. https://berkelland.staging.forus.io/products

# Input data

1. Product information
    * Title
    * Description
    * Price
    * New price
    * Amount / unlimited stock
    * Expiration date
    * Category

# Prerequisites

1. No information

# Instructions

<table>
<tr><th>Step No.</th><th>Step description</th><th>Expected result</th></tr>
<tr><td>1.</td><td>Go to https://staging.forus.io/provider</td><td>{what a tester should see when they do that}</td></tr>
<tr><td>2.</td><td>Go to https://staging.forus.io/provider and click <b>Login</b></td><td>Login modal should open</td></tr>
<tr><td>3.</td><td>Use e-mail or Me-app to login</td><td>Did you choose e-mail? Than you should receive link to login. <br> Did you use the Me-app? Than you should be redirected to the provider dashboard</td></tr>
<tr><td>4.</td><td>Click on <b>Aanbiedingen</b> on the left side of the menu.</td><td>The page to add a product should open</td></tr>
<tr><td>5.</td><td>Enter the requested data and lick on <b>Bevestig</b></td><td>Redirection to the product overview page</td></tr>
<tr><td>6.</td><td>Go to https://staging.berkelland.forus/products and check if your product is added to the webshop</td><td>You should find your just added product.</td></tr>
</table>

# Result

* pass

# Notes

* after clicking on aanbiedingen, you need to click on aanbieding toevoegen, this is not specified in the instructions

**Comment by marten410** [comment]
Het ging prima. niks bijzonders

**Comment by MariskaMartens** [comment]
Result:
Fail(?)

Notes:
- Step 3: E-mail login werkt prima. Me-app login werkt ook prima. Hoewel, de QR-code scanner sluit niet automatisch af na het scannen van een code als je inlogt, dus hij probeerde dubbel te scannen terwijl ik al ingelogd was en gaf toen onderaan een kleine foutmelding in hetzelfde formaat tekst als toen de inlogpoging gelukt was. Dit is dus geen bug ofzo, maar misschien is het een idee om automatisch de QR-code scanner te stoppen zodra iemand ingelogd is.
- Step 6: Ik zie mijn product niet in de webshop. Misschien heb ik iets verkeerds gedaan? Ik heb de categorieën geprobeerd te bewerken maar ik zie mijn aanbieding nog steeds niet op https://berkelland.staging.forus.io/products . Zie foto's hieronder van wat ik gedaan heb.

Foto 1: Product aangemaakt
![test24febb2](https://user-images.githubusercontent.com/58296023/75156468-8031da00-5712-11ea-9f7b-f5e64c2f9a76.png)

Foto 2: Bevestiging dat ik product aanmaak
![test24febb3](https://user-images.githubusercontent.com/58296023/75156469-80ca7080-5712-11ea-9fa7-1f0f5e7bc8f2.png)

Foto 3: Bij mijn aanbiedingen staat hij er bij
![test24febb4](https://user-images.githubusercontent.com/58296023/75156470-80ca7080-5712-11ea-8cdc-b09fbbbddb4a.png)

Foto 4: Bij de aanbiedingen op de site staat hij er niet bij
![test24febb5](https://user-images.githubusercontent.com/58296023/75156471-80ca7080-5712-11ea-9a95-2c086660e796.png)
